spring:
  datasource:
    url: jdbc:mysql://teamc-db.cmadu8gaa330.ap-northeast-1.rds.amazonaws.com:3306/TeamC
    username: admin
    password: te4ateamc
    driver-class-name: com.mysql.cj.jdbc.Driver
