spring:
  datasource:
    url: jdbc:mysql://35.78.154.17:3306/teamkadai10db
    username: ec2-user
    password: te4ateamc
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        '[hibernate.id.new_generator_mappings]': false